### ISSUE TITLE
cabal: Could not resolve dependencies

### ISSUE THREAD

**Issue by reedrosenbluth** [5outh/Bang#6]
I can't seem to get cabal to install this library. Here's the error:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: Bang-0.1.1.0 (user goal)
trying: base-4.8.1.0/installed-075... (dependency of Bang-0.1.1.0)
next goal: time (dependency of Bang-0.1.1.0)
rejecting: time-1.5.0.1/installed-710..., 1.5.0.1, 1.5 (conflict: Bang =>
time>=1.4.2 && <1.5)
trying: time-1.4.2
next goal: deepseq (dependency of time-1.4.2)
rejecting: deepseq-1.4.1.1/installed-5de..., 1.4.1.2, 1.4.1.1, 1.4.1.0,
1.4.0.0 (conflict: time => deepseq>=1.1 && <1.4)
rejecting: deepseq-1.3.0.2 (conflict: base==4.8.1.0/installed-075..., deepseq
=> base>=4.3 && <4.8)
trying: deepseq-1.3.0.1
next goal: array (dependency of deepseq-1.3.0.1)
rejecting: array-0.5.1.0/installed-d42..., 0.5.1.0, 0.5.0.0 (conflict: deepseq
=> array>=0.1 && <0.5)
rejecting: array-0.4.0.1 (conflict: base==4.8.1.0/installed-075..., array =>
base>=4.2 && <4.7)
rejecting: array-0.4.0.0 (conflict: base==4.8.1.0/installed-075..., array =>
base>=4.2 && <4.6)
rejecting: array-0.3.0.3 (conflict: base==4.8.1.0/installed-075..., array =>
base>=4.2 && <4.5)
rejecting: array-0.3.0.2, 0.3.0.1 (conflict: base==4.8.1.0/installed-075...,
array => base>=4.2 && <4.4)
rejecting: array-0.3.0.0 (conflict: base==4.8.1.0/installed-075..., array =>
base>=3 && <4.4)
rejecting: array-0.2.0.0, 0.1.0.0 (conflict: base==4.8.1.0/installed-075...,
array => base<4.3)
Dependency tree exhaustively searched.
```

**Comment by 5outh** [comment]
Thank you for your feedback! I'll look into it soon, and specifically I'd like to get the library building with `stack` soon.

Have you tried installing it into a sandbox, by the way? That would narrow down some issues related to "cabal hell"

**Comment by reedrosenbluth** [comment]
Sandbox doesn't appear to change anything

**Comment by 5outh** [comment]
@reedrosenbluth Good to know, I'll see if I can find some time this weekend to patch this up.

**Comment by reedrosenbluth** [comment]
Thanks!

**Comment by 5outh** [comment]
I've been trying to get this working with stack; unfortunately I'm running into an error mentioned here https://github.com/commercialhaskell/stack/issues/740 regarding `hmidi`. Not sure what the solution is yet.

**Comment by samdoshi** [comment]
@reedrosenbluth looks like you're building with `GHC 7.10.2` which comes with `base-4.8.1.0`, which is in conflict with `time < 1.5` (via `deepseq`).

Either: switch to `GHC 7.8.4` (or `lts-2.22` if you're using `stack`), or @5outh could fiddle with the package bounds to get it to compile on `7.10.2`.

@5outh I'm not getting the linking error anymore using `OSX 10.10` and `stack 0.1.6.0`, but the issue related to the `framework` option in the `.cabal` file, see here haskell/cabal#2715 for more info, the `otool -L` command is very useful for debugging.

I've also submitted #7 to add a working `stack.yaml`, it's `lts-2.22` / `GHC 7.84`, let me know if you want me to get an `lts-3` version working instead.

**Comment by 5outh** [comment]
@samdoshi Cool! Using GHC 7.8.4 is fine for now. Since it's a somewhat standalone library, I think this is fine. Thanks for the PR as well :tada:

**Comment by 5outh** [comment]
Should be fixed now!

**Comment by samdoshi** [comment]
The only thing to watch out for with 7.8 is that it doesn't work on El Capitan at the moment, 7.8.5 is supposed to be out at some point to resolve that.

Cool project by the way :+1:

**Comment by 5outh** [comment]
Good to know, thanks again :)

**Comment by 5outh** [comment]
New version is up which should work with `stack install`. Waiting on stack to recognize the new package version; I'll close it when I can successfully `stack install` globally.

**Comment by samdoshi** [comment]
Just had a quick go trying to get this to build with 7.10.2 and lts-3.11, looks like that framework linking bug isn't fixed after all. It appears to fixed in both GHC and Cabal but unreleased as yet.

https://ghc.haskell.org/trac/ghc/ticket/10568

**Comment by 5outh** [comment]
Good to know, I'll keep an eye on the ticket.

**Comment by 5outh** [comment]
`stack install Bang --resolver=lts-2.22` should work now.

**Comment by reedrosenbluth** [comment]
So this won't work with GHC 7.10.2?

**Comment by 5outh** [comment]
Unfortunately no, not yet. :(
